server:
  port: 8080
  servlet:
    context-path: /weblogin

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/weblogin"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "ICG/Q06Z+yAYXEgIFoOBkXlMKkv6B3dFqj5x3M1R3YAYgmbRl/PNVVZ9+uQDIErH"
logging:
  level:
    org.springframework.security: DEBUG
